version: "3"

services:
  app:
    build: ./
    environment:
      - REDIS_URL="redis://cache"
    ports:
      - "5000:5000"
    container_name: merkle-app

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
